<?php

/**
 * @file
 * Implement socialshare support for Drupal
 */

/**
 * Implements hook_theme().
 */
function socialloginandsocialshare_share_theme() {
  return array(
    'socialloginandsocialshare_social_share' => array(
      'variables' => array(
        'node' => NULL,
        'position' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_block().
 */
function socialloginandsocialshare_share_block($op = 'list', $delta = '', $edit = array()) {
  switch ($op) {
    case 'list':
      return socialloginandsocialshare_share_block_info();
    case 'view':
      return socialloginandsocialshare_share_block_view($delta);
  }
}

/**
 * Implements hook_block_info().
 */
function socialloginandsocialshare_share_block_info() {
  $blocks['sharing'] = array(
    'info' => t('Social Sharing'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function socialloginandsocialshare_share_block_view($delta) {
  if (!user_access('administer site configuration')) {
    $block = array();
    $output = '';
    module_load_include('inc', 'socialloginandsocialshare', 'socialloginandsocialshare.functions');

    if (variable_get('socialloginandsocialshare_enable_horizontal_share', '') == 1) {
      if (!socialloginandsocialshare_check_jsexist('lrsocialshare')) {
        socialloginandsocialshare_horizontal_script_code();
      }

      $output .= socialloginandsocialshare_horizontal_sharing_div();
    }

    if (variable_get('socialloginandsocialshare_enable_vertical_share', '') == 1) {
      if (!socialloginandsocialshare_check_jsexist('lrverticalsocialshare')) {
        socialloginandsocialshare_vertical_script_code();
      }

      $output .= socialloginandsocialshare_vertical_sharing_div();
    }

    $block['content'] = $output;
    return $block;
  }
}

/**
 * Theme social share.
 */
function theme_socialloginandsocialshare_social_share($node) {
  $output = '';
  $item = menu_get_object('node', 1, NULL);

  $item_nid = (!empty($item->nid) ? $item->nid : '');
  $item_title = (!empty($item->title) ? $item->title : '');

  $shareall_withexcept = variable_get('socialshare_show_pages', '');
  $node_withexcept = variable_get('socialshare_show_exceptpages', '');

  $node_except = explode(',', $node_withexcept);

  $vertical_shareall_withexcept = variable_get('socialshare_vertical_show_pages', '');
  $vertical_node_withexcept = variable_get('socialshare_vertical_show_exceptpages', '');

  $vertical_node_except = explode(',', $vertical_node_withexcept);

  //Add horizontal script and add sharing div to node.
  if (variable_get('socialloginandsocialshare_enable_horizontal_share', '') == 1) {
    if ($node['position'] == 'horizontal') {
      if (!socialloginandsocialshare_check_jsexist('lrsocialshare')) {
        socialloginandsocialshare_horizontal_script_code();
      }

      if ($shareall_withexcept == 0) {
        if (!in_array($item_nid, $node_except) AND ! in_array($item_title, $node_except)) {
          $output .= socialloginandsocialshare_horizontal_sharing_div();
        }
      }
      elseif ($shareall_withexcept == 1) {
        if (in_array($item_nid, $node_except) OR in_array($item_title, $node_except)) {
          $output .= socialloginandsocialshare_horizontal_sharing_div();
        }
      }
    }
  }
  //Add vertical script and add sharing div to node.
  if (variable_get('socialloginandsocialshare_enable_vertical_share', '') == 1) {
    if ($node['position'] == 'vertical') {
      if (!socialloginandsocialshare_check_jsexist('lrverticalsocialshare')) {
        socialloginandsocialshare_vertical_script_code();
      }

      if ($vertical_shareall_withexcept == 0) {
        if (!in_array($item_nid, $vertical_node_except) AND ! in_array($item_title, $vertical_node_except)) {
          $output .= socialloginandsocialshare_vertical_sharing_div();
        }
      }
      elseif ($vertical_shareall_withexcept == 1) {
        if (in_array($item_nid, $vertical_node_except) OR in_array($item_title, $vertical_node_except)) {
          $output .= socialloginandsocialshare_vertical_sharing_div();
        }
      }
    }
  }
  return $output;
}

/**
 * Implements hook_nodeapi().
 */
function socialloginandsocialshare_share_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($op == 'view') {
    module_load_include('inc', 'socialloginandsocialshare', 'socialloginandsocialshare.functions');

    if (variable_get('socialloginandsocialshare_enable_horizontal_share', '') == 1) {
      if (!variable_get('socialshare_position_top', 1) and ! variable_get('socialshare_position_bottom', 1)) {
        variable_set('socialshare_position_top', 1);
      }

      if (variable_get('socialshare_position_top', 1)) {
        $node->content['socialshare_top'] = array(
          '#value' => theme('socialloginandsocialshare_social_share', array(
            'node' => $node,
            'position' => 'horizontal'
          )),
          '#weight' => intval(variable_get('socialshare_top_weight', -10)),
        );
      }

      if (variable_get('socialshare_position_bottom', 1)) {
        $node->content['socialshare_bottom'] = array(
          '#value' => theme('socialloginandsocialshare_social_share', array(
            'node' => $node,
            'position' => 'horizontal'
          )),
          '#weight' => intval(variable_get('socialshare_bottom_weight', 10)),
        );
      }
    }

    if (variable_get('socialloginandsocialshare_enable_vertical_share', '') == 1) {
      if (!socialloginandsocialshare_check_jsexist('lrverticalsocialshare')) {
        socialloginandsocialshare_vertical_script_code();
      }
      $node->content['socialshare'] = array(
        '#value' => theme('socialloginandsocialshare_social_share', array('node' => $node, 'position' => 'vertical')),
        '#weight' => 10,
      );
    }
  }
}

/**
 *  Horizontal Social Sharing Script Code.
 */
function socialloginandsocialshare_horizontal_script_code() {
  $share_providers = variable_get('socialloginandsocialshare_rearrange_providers_list', '');
  $socialloginandsocialshare_share_horizontal_images = variable_get('socialloginandsocialshare_share_horizontal_images', '');

  if (empty($share_providers)) {
    variable_set('socialloginandsocialshare_rearrange_providers_list', socialloginandsocialshare_get_default_sharing_networks('socialloginandsocialshare_rearrange_providers_list'));
  }

  if ($socialloginandsocialshare_share_horizontal_images == '0' || $socialloginandsocialshare_share_horizontal_images == '1' || $socialloginandsocialshare_share_horizontal_images == '2' || $socialloginandsocialshare_share_horizontal_images == '3') {

    $interface = 'simpleimage';

    if ($socialloginandsocialshare_share_horizontal_images == '0' || $socialloginandsocialshare_share_horizontal_images == '1') {
      $interface = 'horizontal';
    }

    $size = '16';

    if ($socialloginandsocialshare_share_horizontal_images == '0' || $socialloginandsocialshare_share_horizontal_images == '2') {
      $size = '32';
    }

    $mysettings = array(
      'sharing' => TRUE,
      'lr_interface' => $interface,
      'providers' => implode(',', variable_get('socialloginandsocialshare_rearrange_providers_list', '')),
      'size' => $size,
      'apikey' => trim(variable_get('socialloginandsocialshare_apikey', '')),
      'divwidget' => 'lrsharecontainer',
    );
  }
  else {
    $counter_providers = variable_get('socialcounter_rearrange_providers_list', '');

    if (empty($counter_providers)) {
      variable_set('socialcounter_rearrange_providers_list', socialloginandsocialshare_get_default_sharing_networks('socialcounter_rearrange_providers_list'));
    }

    $provider_list = variable_get('socialcounter_rearrange_providers_list', '');
    $providers = implode(',', $provider_list);

    if ($socialloginandsocialshare_share_horizontal_images == '8' || $socialloginandsocialshare_share_horizontal_images == '9') {
      $interface = 'simple';
    }

    $type = 'horizontal';

    if ($socialloginandsocialshare_share_horizontal_images == '8') {
      $type = 'vertical';
    }

    $mysettings = array(
      'counter' => TRUE,
      'lr_interface' => $interface,
      'providers' => $providers,
      'countertype' => $type,
      'divwidget' => 'lrcounter_simplebox',
    );
  }

  drupal_add_js(array('lrsocialshare' => $mysettings), 'setting');
  drupal_add_js(drupal_get_path('module', 'socialloginandsocialshare') . '/js/socialshare_widget.js', 'external', 'footer');
}

/**
 * Vertical Social Sharing Script Code.
 */
function socialloginandsocialshare_vertical_script_code() {
  module_load_include('inc', 'socialloginandsocialshare', 'socialloginandsocialshare.admin');
  $socialsharing_vertical_images = variable_get('socialloginandsocialshare_share_vertical_images', '');
  $socialshare_vertical_position = variable_get('socialshare_vertical_position', '');
  if ($socialsharing_vertical_images == '4' || $socialsharing_vertical_images == '5') {
    $share_providers = variable_get('socialshare_vertical_rearrange_providers_list', '');

    if (empty($share_providers)) {
      variable_set('socialshare_vertical_rearrange_providers_list', socialloginandsocialshare_get_default_sharing_networks('socialshare_vertical_rearrange_providers_list'));
    }

    $size = '16';

    if ($socialsharing_vertical_images == '4') {
      $size = '32';
    }

    if ($socialshare_vertical_position == '0') {
      $position1 = 'top';
      $position2 = 'left';
    }
    elseif ($socialshare_vertical_position == '1') {
      $position1 = 'top';
      $position2 = 'right';
    }
    elseif ($socialshare_vertical_position == '2') {
      $position1 = 'bottom';
      $position2 = 'left';
    }
    else {
      $position1 = 'bottom';
      $position2 = 'right';
    }

    $mysettings = array(
      'verticalsharing' => TRUE,
      'lr_vertical_interface' => 'Simplefloat',
      'vertical_providers' => implode(',', variable_get('socialshare_vertical_rearrange_providers_list', '')),
      'vertical_size' => $size,
      'vertical_apikey' => trim(variable_get('socialloginandsocialshare_apikey', '')),
      'vertical_position1' => $position1,
      'vertical_position2' => $position2,
      'vertical_divwidget' => 'lrshareverticalcontainer',
    );
  }
  else {
    $counter_providers = variable_get('socialcounter_rearrange_providers_list', '');

    if (empty($counter_providers)) {
      variable_set('socialcounter_rearrange_providers_list', socialloginandsocialshare_get_default_sharing_networks('socialcounter_rearrange_providers_list'));
    }

    $type = 'horizontal';

    if ($socialsharing_vertical_images == '6') {
      $type = 'vertical';
    }

    if ($socialshare_vertical_position == '0') {
      $position1 = 'top';
      $position2 = 'left';
    }
    elseif ($socialshare_vertical_position == '1') {
      $position1 = 'top';
      $position2 = 'right';
    }
    elseif ($socialshare_vertical_position == '2') {
      $position1 = 'bottom';
      $position2 = 'left';
    }
    else {
      $position1 = 'bottom';
      $position2 = 'right';
    }

    $mysettings = array(
      'verticalcounter' => TRUE,
      'vertical_providers' => implode(',', variable_get('socialcounter_vertical_rearrange_providers_list', '')),
      'vertical_countertype' => $type,
      'vertical_position1' => $position1,
      'vertical_position2' => $position2,
      'vertical_divwidget' => 'lrcounter_verticalsimplebox',
    );
  }

  drupal_add_js(array('lrverticalsocialshare' => $mysettings), 'setting');
  drupal_add_js(drupal_get_path('module', 'socialloginandsocialshare') . '/js/socialshare_widget.js', 'external', 'footer');
}

/**
 *
 * Get horizontal div to show sharing widget.
 */
function socialloginandsocialshare_horizontal_sharing_div() {
  $socialsharing_horizontal_images = variable_get('socialloginandsocialshare_share_horizontal_images', '');

  if ($socialsharing_horizontal_images == '0' || $socialsharing_horizontal_images == '1' || $socialsharing_horizontal_images == '2' || $socialsharing_horizontal_images == '3') {
    return '<div class="lrsharecontainer"' . drupal_attributes(array("style" => "z-index: 1000000;")) . '></div>';
  }
  else {
    return '<div class="lrcounter_simplebox"></div>';
  }
}

/**
 *
 * Get vertical div to show sharing widget.
 */
function socialloginandsocialshare_vertical_sharing_div() {
  $socialsharing_vertical_images = variable_get('socialloginandsocialshare_share_vertical_images', '');

  if ($socialsharing_vertical_images == '4' || $socialsharing_vertical_images == '5') {
    return '<div class="lrshareverticalcontainer"' . drupal_attributes(array("style" => "z-index: 1000000;")) . '></div>';
  }
  else {
    return '<div class="lrcounter_verticalsimplebox"></div>';
  }
}
